// backgrounds.js

export const backgroundAssets = [
  { id: "bg1", name: "Abandoned Building", image: "images/Abandoned-Building.jpg" },
  { id: "bg2", name: "Abandoned Quarry", image: "images/Abandoned-Quarry.jpg" },
  { id: "bg3", name: "Abandoned Village", image: "images/Abandoned-Village.jpg" },
  { id: "bg4", name: "Acid Cave", image: "images/Acid-Cave.jpg" },
  { id: "bg5", name: "Amethyst Fortress", image: "images/Amethyst-Fortress.jpg" },
  { id: "bg6", name: "Ancient Courtyard", image: "images/Ancient-Courtyard.jpg" },
  { id: "bg7", name: "Beach Cove", image: "images/Beach-Cove.jpg" },
  { id: "bg8", name: "Beach Front", image: "images/Beach-Front.jpg" },
  { id: "bg9", name: "Brimstone Path", image: "images/Brimstone-Path.jpg" },
  { id: "bg10", name: "Brimstone Plateu", image: "images/Brimstone-Plateu.jpg" },
  { id: "bg11", name: "Cathedral Ruins", image: "images/Cathedral-Ruins.jpg" },
  { id: "bg12", name: "Demon Lair", image: "images/Demon-Lair.jpg" },
  { id: "bg13", name: "Dessert Ruins", image: "images/Dessert-Ruins.jpg" },
  { id: "bg14", name: "Farm", image: "images/Farm.jpg" },
  { id: "bg15", name: "Farm 2", image: "images/Farm-2.jpg" },
  { id: "bg16", name: "Forest Glade", image: "images/Forest-Glade.jpg" },
  { id: "bg17", name: "Forest Ruins", image: "images/Forest-Ruins.jpg" },
  { id: "bg18", name: "Forgotten Crypt", image: "images/Forgotten-Crypt.jpg" },
  { id: "bg19", name: "Forgotten Monastery", image: "images/Forgotten-Monastery.jpg" },
  { id: "bg20", name: "Fort", image: "images/Fort.jpg" },
  { id: "bg21", name: "Fort 2", image: "images/Fort-2.jpg" },
  { id: "bg22", name: "Galleon Ship", image: "images/Galleon-Ship.jpg" },
  { id: "bg23", name: "Glacier Castle", image: "images/Glacier-Castle.jpg" },
  { id: "bg24", name: "Haunted Garden", image: "images/Haunted-Garden.jpg" },
  { id: "bg25", name: "Infernal Tomb", image: "images/Infernal-Tomb.jpg" },
  { id: "bg26", name: "Jungle Path", image: "images/Jungle-Path.jpg" },
  { id: "bg27", name: "Jungle Ruins", image: "images/Jungle-Ruins.jpg" },
  { id: "bg28", name: "Jungle Ruins 2", image: "images/Jungle-Ruins-2.jpg" },
  { id: "bg29", name: "Lost Temple", image: "images/Lost-Temple.jpg" },
  { id: "bg30", name: "Market", image: "images/Market.jpg" },
  { id: "bg31", name: "Market 2", image: "images/Market-2.jpg" },
  { id: "bg32", name: "Moat Checkpoint", image: "images/Moat-Checkpoint.jpg" },
  { id: "bg33", name: "Multen Arena", image: "images/Multen-Arena.jpg" },
  { id: "bg34", name: "Nest", image: "images/Nest.jpg" },
  { id: "bg35", name: "Obsidian Fortress", image: "images/Obsidian-Fortress.jpg" },
  { id: "bg36", name: "Reprieve", image: "images/Reprieve.jpg" },
  { id: "bg37", name: "River Crossings", image: "images/River-Crossings.jpg" },
  { id: "bg38", name: "River Fort", image: "images/River-Fort.jpg" },
  { id: "bg39", name: "Rocky Path", image: "images/Rocky-Path.jpg" },
  { id: "bg40", name: "Rose Court", image: "images/Rose-Court.jpg" },
  { id: "bg41", name: "Ship Yard", image: "images/Ship-Yard.jpg" },
  { id: "bg42", name: "Shipwreck", image: "images/Shipwreck.jpg" },
  { id: "bg43", name: "Slate Path", image: "images/Slate-Path.jpg" },
  { id: "bg44", name: "Snow Fort", image: "images/Snow-Fort.jpg" },
  { id: "bg45", name: "Snow Fort 2", image: "images/Snow-Fort-2.jpg" },
  { id: "bg46", name: "Spider Cave", image: "images/Spider-Cave.jpg" },
  { id: "bg47", name: "Spider Dwelling", image: "images/Spider-Dwelling.jpg" },
  { id: "bg48", name: "Spider Fortress", image: "images/Spider-Fortress.jpg" },
  { id: "bg49", name: "Stone Beach", image: "images/Stone-Beach.jpg" },
  { id: "bg50", name: "Twisting Trail", image: "images/Twisting-Trail.jpg" },
  { id: "bg51", name: "Typical Tavern", image: "images/Typical-Tavern.jpg" },
  { id: "bg52", name: "Village", image: "images/Village.jpg" },
  { id: "bg53", name: "War Zone", image: "images/War-Zone.jpg" },
  { id: "bg54", name: "War Zone 2", image: "images/War-Zone-2.jpg" },
  { id: "bg55", name: "Winter Forest", image: "images/Winter-Forest.jpg" },
  { id: "bg56", name: "Winter Forest 2", image: "images/Winter-Forest-2.jpg" },
];